---
-
    name: Automatisacion Droplets en Digital Ocean Cloud
    hosts: localhost
    connection: local
    gather_facts: False 
    tasks:

      - name: Leer variables para la creacion  de nodos
        include_vars: 
          file: host_vars/localhost.yml 

      - name: Verificar SSH-KEY y CREAR si no existe en Digital Ocean
        digital_ocean:
          state: present
          command : ssh
          name: "ansible-agent"
          ssh_pub_key: "{{ lookup('file','~/.ssh/id_rsa.pub') }}"
        register: ssh_result
      - debug:
          msg: "Llave Creada con exito {{ ssh_result.ssh_key.id}}"

      - name: 'creando nodos en Digital Ocean'
        digital_ocean_droplet:
          id: '{{item.id}}'
          image: '{{item.distro}}'
          name: '{{ item.name }}'
          size: '{{item.tamanio}}'
          monitoring: yes
          state: present
          region: '{{item.region}}' 
          wait_timeout: 500
          ssh_keys: 
            - '{{ ssh_result.ssh_key.id }}'
        register: droplets_creados
        loop: '{{ droplets }}'

      - name: Crear hosts file
        copy:
          dest: production
          content: |
              [digital_ocean_cluster]
              {%for new_droplet in droplets_creados.results %}
              {{new_droplet.data.droplet.name}} ansible_host={{new_droplet.data.ip_address}} 
              {% endfor %}
